name: Auto Fix & Restart

on:
  push:
    branches: [ "main" ]

jobs:
  fix_and_restart:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование
        uses: actions/checkout@v4

      - name: Настройка Git (ВАЖНО!)
        run: |
          git config --global user.email "bot@megabot.com"
          git config --global user.name "MegaBot"

      - name: Проверка requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            echo "requests" > requirements.txt
            echo "beautifulsoup4" >> requirements.txt
          fi

      - name: Удаление лишнего
        run: |
          sed -i '/unittest/d' requirements.txt || true

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt || true

      - name: Запуск бота
        run: |
          python main.py || true
